# Generated by Django 2.2.6 on 2019-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='last updated')),
                ('price_per_unit', models.IntegerField(default=0)),
                ('unit_tye', models.CharField(choices=[('UNIT', 'unit'), ('LB', 'pound'), ('CUP', 'cup')], default='UNIT', max_length=4)),
            ],
        ),
    ]
