# Generated by Django 2.2.6 on 2019-11-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date created')),
                ('updated', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last updated')),
                ('price_per_unit', models.IntegerField(default=0)),
                ('unit_tye', models.CharField(choices=[('UNIT', 'unit'), ('LB', 'pound'), ('CUP', 'cup')], default='UNIT', max_length=4)),
                ('producer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Producer')),
            ],
        ),
    ]
