# Generated by Django 2.2.6 on 2019-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191023_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last updated'),
        ),
    ]
